package link

import (
	"fmt"
	"regexp"
	"strings"

	"goc/frontend"
)

// Emit produces the whole assembly file: the entry stub, the back end's
// function bodies, and the data sections. It is the single place the
// non-C parts of the image are decided, so both back ends produce the same
// program from the same source.
//
// The order of what follows is not arbitrary. The stub comes first because the
// PE/ELF entry point has to be at a known place; the bodies follow it; the
// sections come last because they are addressed by label, not by position.
func Emit(d *Data) (string, error) {
	var out strings.Builder
	out.WriteString("; generated by goc -- assembled by goa, no gcc involved\n")
	out.WriteString("section .text\n")
	out.WriteString("global _start\n")
	if !d.Linux && d.WinGUI {
		out.WriteString("subsystem windows\n")
	}
	out.WriteString("\n")
	for _, e := range sortImports(d.Imports) {
		out.WriteString(e)
	}
	out.WriteString("\n")

	// Bind every pointer slot initialised by a string literal before main runs.
	// goa has no data relocations, so a pointer value cannot live in .data; the
	// entry stub instead computes each string's address with lea and writes it
	// into the (zero-filled) pointer slot. This covers top-level globals, static
	// locals, and char* members nested anywhere inside a braced initialiser.
	for _, g := range d.Program.Globals {
		if d.NeedsSlotBinding != nil && !d.NeedsSlotBinding(d.Globals[g.Name]) {
			continue
		}
		walkGlobalInit(d, g.Typ, g.Init, d.Globals[g.Name], 0)
	}
	for _, se := range d.Statics {
		walkGlobalInit(d, se.Decl.Typ, se.Decl.Init, se.Label, 0)
	}
	var strInit strings.Builder
	for _, si := range d.StringSlots {
		// lea rax,[rip+glab] -- address of the pointer slot
		// lea rdx,[rip+slab] -- address of the string constant
		// mov [rax+off],rdx -- store the string pointer into the slot
		fmt.Fprintf(&strInit, "\tlea rax, [rip+%s]\n\tlea rdx, [rip+%s]\n\tmov [rax+%d], rdx\n",
			si.Global, si.String, si.Offset)
	}
	for _, fi := range d.FuncSlots {
		// Same dance for a function-pointer slot: goa cannot relocate a
		// code address in .data either, so the .data image stays zero and
		// the entry stub stores the function's address at startup.
		fmt.Fprintf(&strInit, "\tlea rax, [rip+%s]\n\tlea rdx, [rip+%s]\n\tmov [rax+%d], rdx\n",
			fi.Global, fi.Func, fi.Offset)
	}
	for _, ai := range d.ArraySlots {
		// Bind a pointer slot to the address of a global/static array. goa
		// has no data relocations, so the address is computed with lea at
		// startup and written into the (zero-filled) slot.
		fmt.Fprintf(&strInit, "\tlea rax, [rip+%s]\n\tlea rdx, [rip+%s]\n\tmov [rax+%d], rdx\n",
			ai.Global, ai.Array, ai.Offset)
	}

	// Entry stub: align the stack, run main, and hand its return value to the
	// platform's exit routine. Linux needs no shadow space and exits through
	// the `exit` syscall stub; Windows uses ExitProcess.
	out.WriteString("_start:\n")
	// The SysV entry stack holds argc at [rsp] and argv just above it; capture
	// them in callee-saved regs before realigning rsp. On Windows those slots
	// are garbage, but reading them is harmless and the registers are
	// overwritten before main is reached.
	out.WriteString("\tmov r12, [rsp]\n")
	out.WriteString("\tlea r13, [rsp+8]\n")
	out.WriteString("\tand rsp, -16\n")
	if d.Linux && len(d.TLSVars) > 0 {
		// Point the fs base at the .tls block (arch_prctl ARCH_SET_FS=0x1002)
		// so the main thread's TLS variables are reachable through the fs
		// segment. arch_prctl is emitted inline (mov rax,158; syscall).
		out.WriteString("\tlea rsi, [rip+__tls_start]\n")
		out.WriteString("\tmov rdi, 0x1002\n")
		out.WriteString("\tmov rax, 158\n")
		out.WriteString("\tsyscall\n")
	}
	out.WriteString(strInit.String())
	if d.Linux {
		out.WriteString("\tmov rdi, r12\n")
		out.WriteString("\tmov rsi, r13\n")
		out.WriteString("\tcall " + d.Entry.Func + "\n")
		out.WriteString("\tmov rdi, rax\n")
		out.WriteString("\tcall " + d.Entry.Exit + "\n\n")
	} else {
		out.WriteString("\tsub rsp, 48\n")
		// A WinMain entry takes the command line as LPWSTR (wWinMain) or
		// LPSTR (WinMain), with argv[0] already stripped (MSVC CRT contract),
		// so the stub calls the matching goclib helper rather than
		// GetCommandLine directly.
		cmdLineFn := "__goclib_lp_cmdline_a"
		if d.Entry.Wide {
			cmdLineFn = "__goclib_lp_cmdline_w"
		}
		switch {
		case d.Entry.TakesArgs:
			// A PE entry point receives no argc/argv, so build them from
			// GetCommandLineA via the goclib helper before main runs. Skipped
			// for main(void) programs -- the back end pulls the helper in
			// only when main declares parameters.
			out.WriteString("\tlea rcx, [rsp+32]\n")
			out.WriteString("\tcall __goclib_get_args\n")
			out.WriteString("\tmov rcx, rax\n")
			out.WriteString("\tmov rdx, [rsp+32]\n")
			out.WriteString("\tcall " + d.Entry.Func + "\n")
		case d.Entry.IsGUI:
			// WinMain(HINSTANCE, HINSTANCE, LPSTR, int) / wWinMain(..., LPWSTR, int).
			// The OS hands the PE entry point nothing, so synthesise the
			// arguments the way the MSVC CRT would: hInstance from
			// GetModuleHandleA(NULL), hPrevInstance always NULL (that is what
			// Win16-era compatibility means, and the CRT has passed NULL there
			// since Windows 2000), the full command line unparsed, and
			// nCmdShow from the STARTUPINFO. The STARTUINFOW fetch needs the
			// PEB, which is not reachable from user32/gdi32 alone, so the
			// standard SW_SHOWDEFAULT (10) is used -- it is what the docs
			// recommend when the caller has no better information, and it
			// defers to the user's ShellExecute "start in" preference.
			out.WriteString("\txor rcx, rcx\n")
			out.WriteString("\tcall GetModuleHandleA\n")
			out.WriteString("\tmov rcx, rax\n") // hInstance
			out.WriteString("\txor rdx, rdx\n") // hPrevInstance = NULL
			out.WriteString("\tcall " + cmdLineFn + "\n")
			out.WriteString("\tmov r8, rax\n") // lpCmdLine
			out.WriteString("\tmov r9d, 10\n") // nCmdShow = SW_SHOWDEFAULT
			out.WriteString("\tcall " + d.Entry.Func + "\n")
		default:
			out.WriteString("\tcall " + d.Entry.Func + "\n")
		}
		out.WriteString("\tmov rcx, rax\n")
		out.WriteString("\tcall " + d.Entry.Exit + "\n\n")
	}
	out.WriteString(d.Body)

	// frontend.Program-level (global / static) variables live in writable sections,
	// referenced via rip. Zero-initialised globals go to .bss (no file bytes,
	// zero-filled by the loader), which shrinks the on-disk image without
	// changing the run-time layout; non-zero globals stay in .data. Only
	// constant integer initialisers are supported today (goclib's globals are
	// all simple constants). Arrays are zero-filled for their full byte size so
	// rip-relative indexing works. Built-in library globals come last, and only
	// those the program actually referenced.
	if len(d.Program.Globals) > 0 || len(d.Statics) > 0 || len(d.LibGlobalsUsed) > 0 || len(d.TLSVars) > 0 {
		// Decide which sections we actually need so we don't open an empty one.
		needData := false
		needBss := false
		checkZero := func(g *frontend.DeclStmt) {
			if g.IsTLS {
				return
			}
			if d.zeroInit(g) {
				needBss = true
			} else {
				needData = true
			}
		}
		for _, g := range d.Program.Globals {
			checkZero(g)
		}
		for _, se := range d.Statics {
			checkZero(se.Decl)
		}
		for _, g := range d.LibGlobals {
			if d.LibGlobalsUsed[g.Name] {
				checkZero(g)
			}
		}
		if needData {
			out.WriteString("\nsection .data\n")
			for _, g := range d.Program.Globals {
				if g.IsTLS || d.zeroInit(g) {
					continue
				}
				if !d.needsDefinition(d.Globals[g.Name]) {
					continue
				}
				if err := emitGlobalVar(&out, g, d.Globals[g.Name]); err != nil {
					return "", err
				}
			}
			for _, se := range d.Statics {
				if d.zeroInit(se.Decl) {
					continue
				}
				if err := emitGlobalVar(&out, se.Decl, se.Label); err != nil {
					return "", err
				}
			}
			for _, g := range d.LibGlobals {
				if !d.LibGlobalsUsed[g.Name] || d.zeroInit(g) {
					continue
				}
				if err := emitGlobalVar(&out, g, d.Globals[g.Name]); err != nil {
					return "", err
				}
			}
		}
		if needBss {
			out.WriteString("\nsection .bss\n")
			for _, g := range d.Program.Globals {
				if g.IsTLS || !d.zeroInit(g) {
					continue
				}
				if !d.needsDefinition(d.Globals[g.Name]) {
					continue
				}
				emitGlobalBSS(&out, g, d.Globals[g.Name])
			}
			for _, se := range d.Statics {
				if !d.zeroInit(se.Decl) {
					continue
				}
				emitGlobalBSS(&out, se.Decl, se.Label)
			}
			for _, g := range d.LibGlobals {
				if !d.LibGlobalsUsed[g.Name] || !d.zeroInit(g) {
					continue
				}
				emitGlobalBSS(&out, g, d.Globals[g.Name])
			}
		}
		if len(d.TLSVars) > 0 {
			// TLS index slot, consumed by the Windows PE loader. The OS assigns
			// this module's TLS index and writes it here at load time; the code
			// generated for _Thread_local reads it to locate the thread's TLS
			// block via gs:0x58. Zero is the right starting value (and is also
			// what the loader overwrites). It lives in a real .data slot (not
			// .bss) so the loader's write has a backing virtual address. The
			// section is reopened unconditionally: if the .bss block above ran
			// (needBss), the current section would otherwise be .bss and the
			// slot would land there, invisible to the loader's TLS write.
			out.WriteString("\nsection .data\n")
			out.WriteString("G_goc_tls_index dq 0\n")
		}
	}

	// Thread-local storage: every _Thread_local variable (global or static
	// local) is laid out in the .tls section, one 8-aligned block per thread.
	// __tls_start names the section base; each variable carries its own label so
	// the access code can lea it (Linux) or compute gs:[0x58]+offset (Windows).
	if len(d.TLSVars) > 0 {
		out.WriteString("\nsection .tls\n")
		out.WriteString("__tls_start:\n")
		pos := 0
		for _, t := range d.TLSVars {
			if pos < t.Offset {
				out.WriteString(fmt.Sprintf("db %d dup(0)\n", t.Offset-pos))
				pos = t.Offset
			}
			if err := emitGlobalVar(&out, t.Decl, t.Label); err != nil {
				return "", err
			}
			pos += tlsAlignedSize(t.Decl.Typ)
		}
	}

	if len(d.Strings) > 0 {
		out.WriteString("\nsection .rdata\n")
		for i := range d.Strings {
			lab := fmt.Sprintf("LC%d", i)
			if d.Strings[i].Wide {
				// L"..." is UTF-16LE: emit the code units verbatim and a
				// 2-byte NUL terminator (one extra byte would leave the final
				// wchar_t half-initialised). encodeStr escapes each byte.
				out.WriteString(fmt.Sprintf("%s db \"%s\", 0, 0\n", lab, encodeStr([]byte(d.Strings[i].Text))))
			} else {
				out.WriteString(fmt.Sprintf("%s db \"%s\", 0\n", lab, encodeStr([]byte(d.Strings[i].Text))))
			}
		}
	}
	if len(d.Doubles) > 0 {
		out.WriteString("\nsection .rdata\n")
		for _, v := range d.Doubles {
			out.WriteString(fmt.Sprintf("%s dq %s\n", v.Label, formatDouble(v.Value)))
		}
	}
	if len(d.BigWords) > 0 {
		out.WriteString("\nsection .rdata\n")
		for i, words := range d.BigWords {
			lab := fmt.Sprintf("LBIG%d", i)
			parts := make([]string, len(words.Words))
			for j, w := range words.Words {
				parts[j] = fmt.Sprintf("0x%x", w)
			}
			out.WriteString(fmt.Sprintf("%s dq %s\n", lab, strings.Join(parts, ", ")))
		}
	}
	asm := out.String()
	if d.Opt == 0 {
		asm = peepholeASM(asm)
	}
	return asm, nil
}

// peepholeASM applies a few safe, textual optimisations to the generated
// assembly before it reaches goa. It is the -O0 path: rewriting the final
// text keeps that level byte-identical to the legacy pipeline. -O1 and above
// run peepholeIR on the instruction stream instead (and leave inline __asm
// alone, unlike this pass, which happily rewrites a user's "mov eax, 0").
// The rewrites are purely local and never touch labels, offsets, or control
// flow. The main one
// replaces `mov <reg>, 0` with `xor <reg32>, <reg32>`: the latter zeroes the
// whole 64-bit register (high bits included) in 2 bytes instead of the 7-byte
// `mov rax, 0`, and goc emits an enormous number of these.
var zeroMovRe = regexp.MustCompile(`(?m)^(\s*)mov\s+([a-z0-9]+)\s*,\s*0\s*$`)

func peepholeASM(s string) string {
	return zeroMovRe.ReplaceAllStringFunc(s, func(line string) string {
		m := zeroMovRe.FindStringSubmatch(line)
		if m == nil {
			return line
		}
		if r := gpReg32(m[2]); r != "" {
			return m[1] + "xor " + r + ", " + r
		}
		return line
	})
}

// gpReg32 maps a general-purpose integer register (either spelling) to its
// 32-bit form, or "" if the operand is not a rewritable integer register
// (a memory operand, rsp/rbp, or an FP register).
func gpReg32(reg string) string {
	switch reg {
	case "rax", "eax":
		return "eax"
	case "rbx", "ebx":
		return "ebx"
	case "rcx", "ecx":
		return "ecx"
	case "rdx", "edx":
		return "edx"
	case "rsi", "esi":
		return "esi"
	case "rdi", "edi":
		return "edi"
	case "r8", "r8d":
		return "r8d"
	case "r9", "r9d":
		return "r9d"
	case "r10", "r10d":
		return "r10d"
	case "r11", "r11d":
		return "r11d"
	case "r12", "r12d":
		return "r12d"
	case "r13", "r13d":
		return "r13d"
	case "r14", "r14d":
		return "r14d"
	case "r15", "r15d":
		return "r15d"
	}
	return ""
}
