/* Generates the golden bit patterns for tests/portability_cases/longdouble.c.
 *
 * Host-only: it is compiled by gcc and computes every expected value with
 * __float128, i.e. libgcc's own binary128. gcc's plain `long double` is the
 * x87 80-bit format on x86-64 and is NOT a bit-level reference for goc's, so
 * the expectations cannot be produced by writing the same source with long
 * double and running it under gcc -- that is the whole reason this file exists.
 *
 *   gcc -std=c11 -O2 tests/fp128/ld_gold.c -o /tmp/ld_gold && /tmp/ld_gold
 */
#include <stdio.h>
#include <string.h>

typedef __float128 LD;

/* The runtime carries the value as { lo, hi } at offsets 0 and 8, which on a
 * little-endian machine is exactly how the 128-bit pattern reads. */
static void pr(const char *name, LD x) {
    unsigned long long w[2];
    memcpy(w, &x, 16);
    printf("    { \"%s\", 0x%016llxull, 0x%016llxull },\n", name, w[1], w[0]);
}

static void prd(const char *name, double d) {
    unsigned long long u;
    memcpy(&u, &d, 8);
    printf("    { \"%s\", 0x%016llxull, 0 },\n", name, u);
}

static void prf(const char *name, float f) {
    unsigned int u;
    memcpy(&u, &f, 4);
    printf("    { \"%s\", 0x%08xull, 0 },\n", name, u);
}

static void prll(const char *name, long long v) {
    printf("    { \"%s\", 0x%016llxull, 0 },\n", name, (unsigned long long)v);
}

int main(void) {
    LD a = 1.5Q, b = 2.25Q;
    LD third = 1.0Q / 3.0Q;
    LD big = 1e30Q, tiny = 1e-30Q;

    puts("/* generated by tests/fp128/ld_gold.c from gcc's __float128 */");

    /* literals */
    pr("lit 1.5L", 1.5Q);
    pr("lit 0.1L", 0.1Q);
    pr("lit 1e30L", 1e30Q);
    pr("lit 1e-30L", 1e-30Q);
    pr("lit 0x1.8p3L", 0x1.8p3Q);
    pr("lit 3.14159265358979323846264338327950288L", 3.14159265358979323846264338327950288Q);

    /* arithmetic */
    pr("1.5+2.25", a + b);
    pr("1.5-2.25", a - b);
    pr("1.5*2.25", a * b);
    pr("1.5/2.25", a / b);
    pr("1/3", third);
    pr("-(1.5)", -a);
    pr("1e30*1e-30", big * tiny);
    pr("1e30+1e-30", big + tiny);
    pr("1e30/0", big / (LD)0.0Q);
    pr("0/0", (LD)0.0Q / (LD)0.0Q);
    pr("1e30*1e30", big * big);

    /* mixed operands: the usual conversions widen to long double */
    pr("ld+double", a + 0.5);
    pr("double+ld", 0.5 + a);
    pr("ld+float", a + 0.5f);
    pr("ld+int", a + 7);
    pr("ld+longlong", a + 7LL);
    pr("ld+uint", a + 7u);

    /* compound assignment */
    {
        LD x = a;
        x += b;
        pr("x+=b", x);
        x *= (LD)2.0Q;
        pr("x*=2", x);
    }

    /* explicit conversions in */
    pr("(ld)double", (LD)0.1);
    pr("(ld)float", (LD)0.1f);
    pr("(ld)int", (LD)(-42));
    pr("(ld)uint", (LD)4000000000u);
    pr("(ld)ll", (LD)(-9007199254740993LL));

    /* Conversions out. These are checked in the TARGET type's own bit
     * pattern, not as a long double, so they get their own table:
     *   DOUBLES / FLOATS / LONGS below. */
    puts("/* ---- doubles ---- */");
    prd("(double)1.5L", (double)a);
    prd("(double)1/3", (double)third);
    prd("(double)1e30", (double)big);
    prd("(double)1e-30", (double)tiny);
    puts("/* ---- floats ---- */");
    prf("(float)1.5L", (float)a);
    prf("(float)1/3", (float)third);
    puts("/* ---- longs ---- */");
    prll("(long long)1.5L", (long long)a);
    prll("(long long)-1.5L", (long long)(-a));
    prll("(long long)1e30L", (long long)big);
    prll("(unsigned long long)1e30L", (unsigned long long)big);
    prll("(int)-1.5L", (int)(-a));
    prll("(unsigned)-1.5L", (unsigned)(-a));

    return 0;
}
