/* goclib mathl.c -- the long double (binary128) half of <math.h> (#50b).
 *
 * Every function here is written in ORDINARY C OVER `long double', not in
 * calls to the goc_tf_* runtime: goc lowers long double arithmetic to that
 * runtime itself (#48), gocl lowers it to LLVM fp128 (#47), and a host
 * compiler gets its own native long double. One source, three back ends, no
 * #ifdef -- which is the whole point of having the type.
 *
 * The constants below are exact to the bit, generated by
 * tools/gen_ldconst.py (integer arithmetic, no float anywhere in the
 * pipeline). The transcendentals split each constant into a HI part (65
 * significant bits) and a LO part that is EXACTLY value - HI, so
 *   x - k*HI - k*LO
 * is a faithful argument reduction: without the split, the reduction would
 * throw away ~48 bits of the constant every time k is large.
 *
 * The handful of functions that poke at bits (floor/ceil/nextafter/ilogb/
 * frexp) assume the value's layout is binary128, little-endian: sign in bit
 * 127, 15 exponent bits, 112 fraction bits. That is what goc's long double is
 * on every target by design, and it is also AArch64's and RISC-V's native
 * long double -- but NOT x86-64 gcc's, whose long double is x87 80-bit. So
 * under gcc on x86-64 these five are layout-wrong while the arithmetic ones
 * are fine. goclib's long double story is binary128 throughout; see float.h.
 */
#include <math.h>
#include <float.h>
#include <string.h>

/* ---- constants: see tools/gen_ldconst.py -------------------------------- */
#define LD_LN2       0x1.62e42fefa39ef35793c7673007e6p-1L
#define LD_LN2_HI    0x1.62e42fefa39ef358p-1L
#define LD_LN2_LO    -0x1.b0e2633fe0680000000000000000p-67L
#define LD_LOG2E     0x1.71547652b82fe1777d0ffda0d23ap+0L
#define LD_LN10      0x1.26bb1bbb5551582dd4adac5705a6p+1L
#define LD_LOG10E    0x1.bcb7b1526e50e32a6ab7555f5a68p-2L
#define LD_PI        0x1.921fb54442d18469898cc51701b8p+1L
#define LD_PI_2      0x1.921fb54442d18469898cc51701b8p+0L
#define LD_PI_2_HI   0x1.921fb54442d1846ap+0L
#define LD_PI_2_LO   -0x1.d9cceba3f9200000000000000000p-66L
#define LD_2_OVER_PI 0x1.45f306dc9c882a53f84eafa3ea6ap-1L

/* ---- bit access ---------------------------------------------------------- */
/* 112 fraction bits: the high 48 live in bits 47..0 of hi, the low 64 in lo. */
#define LD_FRAC_HI_MASK 0x0000ffffffffffffULL
#define LD_SIGN_MASK    0x8000000000000000ULL
#define LD_BIAS         16383

static void ld_get(long double x, unsigned long long *hi, unsigned long long *lo) {
    unsigned long long w[2];
    memcpy(w, &x, 16);
    *lo = w[0];
    *hi = w[1];
}

static long double ld_set(unsigned long long hi, unsigned long long lo) {
    unsigned long long w[2];
    long double x;
    w[0] = lo;
    w[1] = hi;
    memcpy(&x, w, 16);
    return x;
}

/* ---- classification helpers (internal) ----------------------------------- */
static int ld_isnan(long double x) { return x != x; }
static int ld_isinf(long double x) { return x > LDBL_MAX || x < -LDBL_MAX; }
static long double ld_nan(void) { return 0.0L / 0.0L; }
static long double ld_inf(void) { return 1.0L / 0.0L; }
static int ld_signbit(long double x) {
    unsigned long long hi, lo;
    ld_get(x, &hi, &lo);
    return (hi >> 63) & 1;
}
/* Unbiased exponent of the value as stored; 0 means subnormal or zero. */
static int ld_expfield(unsigned long long hi) { return (int)((hi >> 48) & 0x7FFF); }

/* 2^e, exactly. Used by ldexp and by exp's reassembly. */
static long double ld_pow2i(int e) {
    unsigned long long hi, lo;
    int bitpos;
    if (e > 16383) return ld_inf();
    if (e >= -16382) return ld_set((unsigned long long)(e + LD_BIAS) << 48, 0);
    if (e < -16494) return 0.0L;
    /* subnormal: 2^e = 2^-16382 * 2^(e+16382), i.e. one fraction bit */
    bitpos = 112 - (-16382 - e);          /* 0..111 */
    hi = 0;
    lo = 0;
    if (bitpos >= 64) hi = 1ULL << (bitpos - 64);
    else              lo = 1ULL << bitpos;
    return ld_set(hi, lo);
}

/* ---- rounding to integer -------------------------------------------------- */
/* trunc by masking: the fraction bits below the binary point are cleared, so
 * nothing here can round in the wrong direction the way (long long)x does. */
static long double ld_trunc(long double x) {
    unsigned long long hi, lo, fhi, flo;
    int e, sh;
    if (ld_isnan(x) || ld_isinf(x) || x == 0.0L) return x;
    ld_get(x, &hi, &lo);
    e = ld_expfield(hi) - LD_BIAS;
    if (e >= 112) return x;               /* no fraction bits left to clear */
    if (e < 0) return ld_set(hi & LD_SIGN_MASK, 0);   /* |x| < 1 -> zero, signed */
    sh = 112 - e;
    fhi = hi & LD_FRAC_HI_MASK;
    flo = lo;
    if (sh >= 64) {
        fhi &= ~((1ULL << (sh - 64)) - 1ULL);
        flo = 0;
    } else {
        flo &= ~((1ULL << sh) - 1ULL);
    }
    return ld_set((hi & ~LD_FRAC_HI_MASK) | fhi, flo);
}

long double truncl(long double x) { return ld_trunc(x); }

long double floorl(long double x) {
    long double t;
    if (ld_isnan(x) || ld_isinf(x) || x == 0.0L) return x;
    t = ld_trunc(x);
    if (t != x && x < 0.0L) t = t - 1.0L;
    return t;
}

long double ceill(long double x) {
    long double t;
    if (ld_isnan(x) || ld_isinf(x) || x == 0.0L) return x;
    t = ld_trunc(x);
    if (t != x && x > 0.0L) t = t + 1.0L;
    return t;
}

/* Round half away from zero (C99 round), and half to even (rint/roundeven).
 * Both go through trunc plus a comparison of the fractional remainder against
 * 1/2, which is exact -- the remainder is a difference of two binary128
 * values that cancel in the high bits. */
static long double ld_round_half(long double x, int to_even) {
    long double t, fr, afr;
    int s;
    if (ld_isnan(x) || ld_isinf(x) || x == 0.0L) return x;
    t = ld_trunc(x);
    if (t == x) return x;
    fr = x - t;
    afr = fr < 0.0L ? -fr : fr;
    s = ld_signbit(x);
    if (afr > 0.5L) {
        t = s ? t - 1.0L : t + 1.0L;
    } else if (afr == 0.5L) {
        int up;
        if (to_even) {
            /* the even neighbour: t is even iff t/2 has no remainder */
            long double h = t * 0.5L;
            up = (h != ld_trunc(h));
        } else {
            up = 1;                       /* away from zero */
        }
        if (up) t = s ? t - 1.0L : t + 1.0L;
    }
    return t;
}

long double roundl(long double x)     { return ld_round_half(x, 0); }
long double rintl(long double x)      { return ld_round_half(x, 1); }
long double nearbyintl(long double x) { return ld_round_half(x, 1); }
long double roundevenl(long double x) { return ld_round_half(x, 1); }

/* ---- absolute value, min/max, sign --------------------------------------- */
long double fabsl(long double x) { return x < 0.0L ? -x : x; }

long double fmaxl(long double x, long double y) {
    if (ld_isnan(x)) return y;
    if (ld_isnan(y)) return x;
    return x > y ? x : y;
}

long double fminl(long double x, long double y) {
    if (ld_isnan(x)) return y;
    if (ld_isnan(y)) return x;
    return x < y ? x : y;
}

long double copysignl(long double x, long double y) {
    unsigned long long hi, lo, yhi, ylo;
    ld_get(x, &hi, &lo);
    ld_get(y, &yhi, &ylo);
    hi = (hi & ~LD_SIGN_MASK) | (yhi & LD_SIGN_MASK);
    return ld_set(hi, lo);
}

long double fdiml(long double x, long double y) {
    long double d;
    if (ld_isnan(x)) return x;
    if (ld_isnan(y)) return y;
    d = x - y;
    return d > 0.0L ? d : 0.0L;
}

/* ---- remainder, splitting, scaling --------------------------------------- */
long double fmodl(long double x, long double y) {
    long double n, r;
    if (ld_isnan(x) || ld_isnan(y) || y == 0.0L || ld_isinf(x)) return ld_nan();
    if (ld_isinf(y)) return x;
    n = ld_trunc(x / y);
    r = x - n * y;
    if (r != 0.0L && ld_signbit(r) != ld_signbit(x)) r = -r;
    return r;
}

long double modfl(long double x, long double *ip) {
    long double t;
    if (ld_isnan(x)) {
        *ip = x;
        return x;
    }
    if (ld_isinf(x)) {
        *ip = x;
        return ld_set((unsigned long long)ld_signbit(x) << 63, 0);   /* signed zero */
    }
    t = ld_trunc(x);
    *ip = t;
    return x - t;
}

long double frexpl(long double x, int *e) {
    unsigned long long hi, lo, fhi, flo;
    int ef, shift = 0;
    if (ld_isnan(x) || ld_isinf(x) || x == 0.0L) {
        *e = 0;
        return x;
    }
    ld_get(x, &hi, &lo);
    ef = ld_expfield(hi);
    /* Subnormal: scale up until the exponent field is nonzero. Each step is a
     * power of two, so no precision is lost on the way. */
    while (ef == 0) {
        x = x * 0x1p64L;
        shift -= 64;
        ld_get(x, &hi, &lo);
        ef = ld_expfield(hi);
    }
    fhi = hi & LD_FRAC_HI_MASK;
    flo = lo;
    *e = ef - LD_BIAS + 1 + shift;
    /* force the exponent field to 16382: |m| in [0.5,1) */
    return ld_set((hi & ~LD_FRAC_HI_MASK & ~((unsigned long long)0x7FFF << 48))
                      | ((unsigned long long)(LD_BIAS - 1) << 48) | fhi, flo);
}

long double ldexpl(long double x, int e) {
    if (ld_isnan(x) || ld_isinf(x) || x == 0.0L) return x;
    /* Scaling by a power of two is exact, so chunking never double-rounds --
     * it only keeps 2^e itself inside the representable range. */
    while (e > 8192)  { x = x * 0x1p8192L;  e -= 8192; }
    while (e < -8192) { x = x * 0x1p-8192L; e += 8192; }
    return x * ld_pow2i(e);
}

long double scalbnl(long double x, int n)  { return ldexpl(x, n); }
long double scalblnl(long double x, long n) {
    if (n > 100000) return ldexpl(x, 100000);
    if (n < -100000) return ldexpl(x, -100000);
    return ldexpl(x, (int)n);
}

/* ---- exponent extraction -------------------------------------------------- */
long double logbl(long double x) {
    unsigned long long hi, lo;
    int ef;
    if (ld_isnan(x)) return x;
    if (ld_isinf(x)) return ld_inf();
    if (x == 0.0L) return -ld_inf();
    ld_get(x, &hi, &lo);
    ef = ld_expfield(hi);
    if (ef == 0) {                     /* subnormal: normalise first */
        int shift = 0;
        while (ld_expfield(hi) == 0) {
            x = x * 0x1p64L;
            shift -= 64;
            ld_get(x, &hi, &lo);
        }
        return (long double)(ld_expfield(hi) - LD_BIAS + shift);
    }
    return (long double)(ef - LD_BIAS);
}

int ilogbl(long double x) {
    if (ld_isnan(x)) return FP_ILOGBNAN;
    if (ld_isinf(x)) return 2147483647;
    if (x == 0.0L) return FP_ILOGB0;
    return (int)logbl(x);
}

/* ---- neighbours ----------------------------------------------------------- */
/* Step the magnitude by one, keeping the sign. The magnitude is the full
 * 112+15 bit field, so incrementing it carries from lo into the exponent --
 * which is exactly how the last finite value becomes infinity. */
static long double ld_step(long double x, int up_magnitude) {
    unsigned long long hi, lo, mhi, mlo;
    int sign;
    ld_get(x, &hi, &lo);
    sign = (int)((hi >> 63) & 1);
    mhi = hi & ~LD_SIGN_MASK;
    mlo = lo;
    if (up_magnitude) {
        mlo += 1;
        if (mlo == 0) mhi += 1;
    } else {
        if (mlo == 0) { mhi -= 1; mlo = 0xFFFFFFFFFFFFFFFFULL; }
        else          { mlo -= 1; }
    }
    return ld_set(mhi | ((unsigned long long)sign << 63), mlo);
}

long double nextafterl(long double x, long double y) {
    if (ld_isnan(x) || ld_isnan(y)) return ld_nan();
    if (x == y) return y;
    if (x == 0.0L) {
        /* C: from a zero the result is the smallest subnormal carrying y's
         * sign -- the direction argument decides, not the zero's own sign
         * (nextafter(+0, -1) is -LDBL_TRUE_MIN). */
        return ld_set(ld_signbit(y) ? LD_SIGN_MASK : 0, 1);
    }
    if (x < y) return ld_step(x, !ld_signbit(x));        /* toward zero if negative */
    return ld_step(x, ld_signbit(x));
}

long double nextupl(long double x) {
    if (ld_isnan(x)) return x;
    if (x == ld_inf()) return x;
    if (x == 0.0L) return ld_set(0, 1);
    return ld_step(x, !ld_signbit(x));
}

long double nextdownl(long double x) {
    if (ld_isnan(x)) return x;
    if (x == -ld_inf()) return x;
    if (x == 0.0L) return ld_set(LD_SIGN_MASK, 1);
    return ld_step(x, ld_signbit(x));
}

/* ---- square root ----------------------------------------------------------- */
/* Newton from a double seed. The seed costs nothing and the iteration triples
 * the correct digits each step, so five steps finish a 113-bit result. The
 * answer is within an ulp of correctly rounded, not guaranteed to be it. */
long double sqrtl(long double x) {
    long double y, r;
    int e, i;
    if (ld_isnan(x) || x == 0.0L) return x;
    if (x < 0.0L) return ld_nan();
    if (ld_isinf(x)) return x;
    y = frexpl(x, &e);                     /* y in [0.5,1) */
    if (e & 1) { y = y * 2.0L; e -= 1; }   /* make e even: sqrt(2^e) is exact */
    r = (long double)sqrt((double)y);
    for (i = 0; i < 5; i++) r = 0.5L * (r + y / r);
    return ldexpl(r, e / 2);
}

long double cbrtl(long double x) {
    long double r, ax;
    int i, neg;
    if (ld_isnan(x) || ld_isinf(x) || x == 0.0L) return x;
    neg = x < 0.0L;
    ax = fabsl(x);
    r = expl(logl(ax) / 3.0L);             /* seed: a few bits is enough */
    for (i = 0; i < 6; i++) r = (2.0L * r + ax / (r * r)) / 3.0L;
    return neg ? -r : r;
}

long double hypotl(long double x, long double y) {
    long double t, big, small, scale;
    int scaled = 0;
    if (ld_isnan(x) || ld_isnan(y)) return ld_nan();
    if (ld_isinf(x) || ld_isinf(y)) return ld_inf();
    big = fabsl(x);
    small = fabsl(y);
    if (big < small) { t = big; big = small; small = t; }
    if (big == 0.0L) return 0.0L;
    /* A subnormal dividend would overflow the ratio before the sqrt sees it,
     * so scale both up by an exact power of two and undo it afterwards. */
    if (big < 0x1p-8000L) {
        big = big * 0x1p8192L;
        small = small * 0x1p8192L;
        scaled = 1;
    }
    if (small == 0.0L) return scaled ? big * 0x1p-8192L : big;
    t = small / big;
    scale = sqrtl(1.0L + t * t);
    return scaled ? big * scale * 0x1p-8192L : big * scale;
}

/* ---- exponentials --------------------------------------------------------- */
/* exp(r) for |r| <= ln2/2 by the Taylor series. 40 terms is past the point
 * where the tail is below 2^-120; the loop leaves as soon as it is. */
static long double ld_exp_series(long double r) {
    long double term = 1.0L, sum = 1.0L;
    int i;
    for (i = 1; i < 40; i++) {
        term = term * r / (long double)i;
        sum = sum + term;
        if (term < 0x1p-120L && term > -0x1p-120L) break;
    }
    return sum;
}

long double expl(long double x) {
    long double k, r, s;
    if (ld_isnan(x)) return x;
    if (x == ld_inf()) return ld_inf();
    if (x == -ld_inf()) return 0.0L;
    /* log(LDBL_MAX) is about 11356.5, and log(LDBL_TRUE_MIN) about -11399 */
    if (x > 11357.0L) return ld_inf();
    if (x < -11400.0L) return 0.0L;
    k = roundl(x * LD_LOG2E);
    r = (x - k * LD_LN2_HI) - k * LD_LN2_LO;
    s = ld_exp_series(r);
    return ldexpl(s, (int)k);
}

long double expm1l(long double x) {
    if (ld_isnan(x) || x == 0.0L) return x;
    if (x == ld_inf()) return ld_inf();
    if (x == -ld_inf()) return -1.0L;
    /* the series is the whole point: expl(x)-1 loses every digit below
     * |x|*2^-113 as x approaches 0 */
    if (x > -0.5L && x < 0.5L) {
        long double term = 1.0L, sum = 0.0L;
        int i;
        for (i = 1; i < 40; i++) {
            term = term * x / (long double)i;
            sum = sum + term;
            if (term < 0x1p-120L && term > -0x1p-120L) break;
        }
        return sum;
    }
    return expl(x) - 1.0L;
}

long double exp2l(long double x) {
    if (ld_isnan(x) || x == ld_inf()) return x == ld_inf() ? ld_inf() : x;
    if (x == -ld_inf()) return 0.0L;
    return expl(x * LD_LN2);
}

long double exp10l(long double x) {
    if (ld_isnan(x) || x == ld_inf()) return x == ld_inf() ? ld_inf() : x;
    if (x == -ld_inf()) return 0.0L;
    return expl(x * LD_LN10);
}

/* ---- logarithms ----------------------------------------------------------- */
/* log(m) for m near 1, via s = (m-1)/(m+1): log(m) = 2*atanh(s). With m in
 * [1/sqrt(2), sqrt(2)), |s| <= 0.1716, so s^2 <= 0.03 and the series dies
 * fast -- about 25 terms for 113 bits. */
static long double ld_log_series(long double s) {
    long double s2 = s * s, term = s, sum = s;
    int i;
    for (i = 1; i < 60; i++) {
        term = term * s2;
        sum = sum + term / (long double)(2 * i + 1);
        if (term < 0x1p-120L && term > -0x1p-120L) break;
    }
    return 2.0L * sum;
}

long double logl(long double x) {
    long double m, s;
    int e;
    if (ld_isnan(x) || x == ld_inf()) return x;
    if (x < 0.0L) return ld_nan();
    if (x == 0.0L) return -ld_inf();
    m = frexpl(x, &e);                     /* m in [0.5,1) */
    if (m < 0x1.6a09e667f3bcc908b2fb1366ea95p-1L) {  /* sqrt(1/2) */
        m = m * 2.0L;
        e -= 1;
    }
    s = (m - 1.0L) / (m + 1.0L);
    return (long double)e * LD_LN2 + ld_log_series(s);
}

long double log1pl(long double x) {
    if (ld_isnan(x)) return x;
    if (x == ld_inf()) return ld_inf();
    if (x < -1.0L) return ld_nan();
    if (x == -1.0L) return -ld_inf();
    /* log(1+x) = 2*atanh(x/(2+x)): no cancellation for small x, which is
     * where logl(1+x) would lose everything below x*2^-113 */
    if (x > -0.29L && x < 0.29L) {
        long double s = x / (2.0L + x);
        return ld_log_series(s);
    }
    return logl(1.0L + x);
}

long double log2l(long double x)  { return logl(x) * LD_LOG2E; }
long double log10l(long double x) { return logl(x) * LD_LOG10E; }

/* ---- powers --------------------------------------------------------------- */
long double powl(long double x, long double y) {
    long long n;
    long double ax, iy, r, b;
    int neg, odd = 0;
    if (y == 0.0L) return 1.0L;            /* includes x == 0, and NaN base */
    if (ld_isnan(x) || ld_isnan(y)) return ld_nan();
    if (ld_isinf(y)) {
        long double a = fabsl(x);
        if (a == 1.0L) return 1.0L;
        if ((a > 1.0L) == (y > 0.0L)) return ld_inf();
        return 0.0L;
    }
    if (ld_isinf(x)) {
        if (y < 0.0L) return x > 0.0L ? 0.0L : 0.0L;
        return x > 0.0L ? ld_inf() : (fmodl(y, 2.0L) == 0.0L ? ld_inf() : -ld_inf());
    }
    ax = fabsl(x);
    neg = x < 0.0L;
    if (neg) {
        iy = roundl(y);
        if (iy != y) return ld_nan();      /* negative base, fractional exponent */
        odd = fmodl(iy, 2.0L) != 0.0L;
    }
    if (ax == 0.0L) return y > 0.0L ? 0.0L : (odd ? -ld_inf() : ld_inf());
    /* An integral exponent of moderate size goes through repeated squaring:
     * exact for pow(x,2) and pow(x,3), which the exp/log path is not. */
    if (y == roundl(y) && fabsl(y) < 1.0e6L) {
        n = (long long)y;
        b = neg ? x : ax;
        if (n < 0) { b = 1.0L / b; n = -n; }
        r = 1.0L;
        while (n > 0) {
            if (n & 1) r = r * b;
            b = b * b;
            n >>= 1;
        }
        return neg && odd ? -fabsl(r) : r;
    }
    r = expl(y * logl(ax));
    return neg && odd ? -r : r;
}

/* ---- trigonometry --------------------------------------------------------- */
/* Argument reduction to |r| <= pi/4 in quarter turns. k stays a long double
 * (not a long long) so a huge argument degrades instead of overflowing the
 * conversion; the two-part constant is what keeps the reduction honest for
 * the arguments that matter. */
static int ld_reduce_pi2(long double x, long double *r) {
    long double k, q;
    k = roundl(x * LD_2_OVER_PI);
    *r = (x - k * LD_PI_2_HI) - k * LD_PI_2_LO;
    q = fmodl(k, 4.0L);
    if (q < 0.0L) q = q + 4.0L;
    return (int)q;
}

static long double ld_sin_series(long double r) {
    long double r2 = r * r, term = r, sum = r;
    int i;
    for (i = 1; i < 40; i++) {
        term = -term * r2 / (long double)((2 * i) * (2 * i + 1));
        sum = sum + term;
        if (term < 0x1p-120L && term > -0x1p-120L) break;
    }
    return sum;
}

static long double ld_cos_series(long double r) {
    long double r2 = r * r, term = 1.0L, sum = 1.0L;
    int i;
    for (i = 1; i < 40; i++) {
        term = -term * r2 / (long double)((2 * i - 1) * (2 * i));
        sum = sum + term;
        if (term < 0x1p-120L && term > -0x1p-120L) break;
    }
    return sum;
}

long double sinl(long double x) {
    long double r;
    int q;
    if (ld_isnan(x) || ld_isinf(x)) return ld_nan();
    q = ld_reduce_pi2(x, &r);
    if (q == 0) return ld_sin_series(r);
    if (q == 1) return ld_cos_series(r);
    if (q == 2) return -ld_sin_series(r);
    return -ld_cos_series(r);
}

long double cosl(long double x) {
    long double r;
    int q;
    if (ld_isnan(x) || ld_isinf(x)) return ld_nan();
    q = ld_reduce_pi2(x, &r);
    if (q == 0) return ld_cos_series(r);
    if (q == 1) return -ld_sin_series(r);
    if (q == 2) return -ld_cos_series(r);
    return ld_sin_series(r);
}

long double tanl(long double x) {
    long double s, c;
    if (ld_isnan(x) || ld_isinf(x)) return ld_nan();
    s = sinl(x);
    c = cosl(x);
    return s / c;
}

/* atan(z) for |z| <= 0.2: the series, ~26 terms for 113 bits. */
static long double ld_atan_series(long double z) {
    long double z2 = z * z, term = z, sum = z;
    int i;
    for (i = 1; i < 60; i++) {
        term = -term * z2;
        sum = sum + term / (long double)(2 * i + 1);
        if (term < 0x1p-120L && term > -0x1p-120L) break;
    }
    return sum;
}

long double atanl(long double x) {
    long double a, r;
    int neg, big = 0;
    if (ld_isnan(x)) return x;
    if (x == 0.0L) return x;
    if (ld_isinf(x)) return x > 0.0L ? LD_PI_2 : -LD_PI_2;
    neg = x < 0.0L;
    a = fabsl(x);
    if (a > 1.0L) { a = 1.0L / a; big = 1; }
    /* halve the angle twice: tan(t/2) = tan(t) / (1 + sec(t)). Two steps take
     * any argument in [0,1] down to tan(pi/16) = 0.199, where the series is
     * fast. */
    a = a / (1.0L + sqrtl(1.0L + a * a));
    a = a / (1.0L + sqrtl(1.0L + a * a));
    r = 4.0L * ld_atan_series(a);
    if (big) r = LD_PI_2 - r;
    return neg ? -r : r;
}

long double atan2l(long double y, long double x) {
    long double r;
    if (ld_isnan(y) || ld_isnan(x)) return ld_nan();
    if (ld_isinf(y)) {
        if (ld_isinf(x)) return ld_signbit(x) ? (ld_signbit(y) ? -0.75L * LD_PI : 0.75L * LD_PI)
                                              : (ld_signbit(y) ? -0.25L * LD_PI : 0.25L * LD_PI);
        return ld_signbit(y) ? -LD_PI_2 : LD_PI_2;
    }
    if (ld_isinf(x)) return x > 0.0L ? (ld_signbit(y) ? -0.0L : 0.0L) : (ld_signbit(y) ? -LD_PI : LD_PI);
    if (x == 0.0L) {
        if (y == 0.0L) return ld_signbit(y) ? (ld_signbit(x) ? -LD_PI : -0.0L)
                                            : (ld_signbit(x) ? LD_PI : 0.0L);
        return ld_signbit(y) ? -LD_PI_2 : LD_PI_2;
    }
    r = atanl(y / x);
    if (x < 0.0L) {
        if (y >= 0.0L) r = r + LD_PI;
        else           r = r - LD_PI;
    }
    return r;
}

long double asinl(long double x) {
    long double ax, t;
    if (ld_isnan(x) || x == 0.0L) return x;
    ax = fabsl(x);
    if (ax > 1.0L) return ld_nan();
    if (ax == 1.0L) return x > 0.0L ? LD_PI_2 : -LD_PI_2;
    t = sqrtl((1.0L - ax) * (1.0L + ax));
    return atanl(x / t);
}

long double acosl(long double x) {
    long double r;
    if (ld_isnan(x)) return x;
    if (x > 1.0L || x < -1.0L) return ld_nan();
    if (x == 1.0L) return 0.0L;
    if (x == -1.0L) return LD_PI;
    /* 2*atan(sqrt((1-x)/(1+x))): the form that stays accurate near x = 1,
     * where pi/2 - asin(x) would cancel. */
    r = 2.0L * atanl(sqrtl((1.0L - x) / (1.0L + x)));
    return r;
}

/* ---- hyperbolic ------------------------------------------------------------ */
long double sinhl(long double x) {
    long double e, ei, ax, r;
    int neg;
    if (ld_isnan(x) || x == 0.0L) return x;
    if (ld_isinf(x)) return x;
    neg = x < 0.0L;
    ax = fabsl(x);
    if (ax > 100.0L) {                    /* 1/e has underflowed away */
        r = 0.5L * expl(ax);
        return neg ? -r : r;
    }
    e = expl(ax);
    ei = 1.0L / e;
    r = 0.5L * (e - ei);
    return neg ? -r : r;
}

long double coshl(long double x) {
    long double e, ei;
    if (ld_isnan(x)) return x;
    if (ld_isinf(x)) return ld_inf();
    if (x == 0.0L) return 1.0L;
    if (fabsl(x) > 100.0L) return 0.5L * expl(fabsl(x));
    e = expl(fabsl(x));
    ei = 1.0L / e;
    return 0.5L * (e + ei);
}

long double tanhl(long double x) {
    long double t;
    int neg;
    if (ld_isnan(x) || x == 0.0L) return x;
    if (ld_isinf(x)) return x > 0.0L ? 1.0L : -1.0L;
    neg = x < 0.0L;
    if (fabsl(x) > 20.0L) return neg ? -1.0L : 1.0L;
    /* expm1l keeps the numerator honest: (e^(2x)-1) would cancel to nothing
     * as x approaches 0 */
    t = expm1l(2.0L * fabsl(x));
    t = t / (t + 2.0L);
    return neg ? -t : t;
}
