/* <math.h>'s long double family (#50b): binary128 mathematics.
 *
 * Two kinds of check.
 *
 * 1. Thirty-significant-digit goldens for the transcendentals, generated by
 *    tools/ldmath_golden.py from a 60-digit decimal reference computed by
 *    DIFFERENT algorithms than mathl.c uses -- Decimal's exp/ln against a
 *    Taylor series with a split constant, atan by subtracting atan(1/2)
 *    against halving the angle twice, pow by exp(y*ln x) against repeated
 *    squaring. A family that is secretly double-precision agrees for the
 *    first 17 digits and fails at the 18th, which is the failure mode this
 *    table exists to catch.
 *
 * 2. Exact checks for the algebraic members: rounding at magnitudes where a
 *    binary128 still has fraction bits (2^80 + 0.5, where a cast to long long
 *    would be meaningless), the neighbour functions at the top and bottom of
 *    the range, and a frexp/ldexp round-trip that reaches into the subnormals.
 *
 * Self-reporting: exit 0 and a final line of "OK".
 */
#include <stdio.h>
#include <math.h>
#include <float.h>
#include <string.h>

static int fails = 0;

static void expect_f(const char *name, long double got, const char *want) {
    char buf[64];
    sprintf(buf, "%.29Le", got);
    if (strcmp(buf, want) != 0) {
        printf("FAIL %s:\n  got  %s\n  want %s\n", name, buf, want);
        fails++;
    }
}

/* Identity checks. Both sides are computed by different paths, so they may
 * differ by an ulp or two of binary128 (1e-34) -- but NOT by the 1e-17 a
 * double-precision implementation would show, which is the only thing these
 * are meant to catch. Comparing them digit for digit at 30 places would fail
 * on the ulp and prove nothing. */
static void expect_near(const char *name, long double got, long double want) {
    long double d = got - want, scale = want < 0.0L ? -want : want;
    if (d < 0.0L) d = -d;
    if (scale == 0.0L) scale = 1.0L;
    if (!(d / scale <= 1.0e-25L)) {
        char b1[64], b2[64];
        sprintf(b1, "%.29Le", got);
        sprintf(b2, "%.29Le", want);
        printf("FAIL %s:\n  got  %s\n  want %s\n", name, b1, b2);
        fails++;
    }
}

/* Exact equality, for the members whose answer is a number a binary128 can
 * hold with no rounding at all. */
static void expect_x(const char *name, long double got, long double want) {
    if (got != want) {
        char b1[64], b2[64];
        sprintf(b1, "%.29Le", got);
        sprintf(b2, "%.29Le", want);
        printf("FAIL %s:\n  got  %s\n  want %s\n", name, b1, b2);
        fails++;
    }
}

static void expect_i(const char *name, long long got, long long want) {
    if (got != want) {
        printf("FAIL %s: got %lld want %lld\n", name, got, want);
        fails++;
    }
}

static int is_nanl(long double x) { return x != x; }

int main(void) {
    long double ip;
    int e, i;
    static const int exps[] = { -16400, -16390, -16000, -1000, -1, 0, 1, 1000, 16000, 16383 };

    /* ---- transcendentals against the decimal reference ------------------- */
    /* generated by tools/ldmath_golden.py -- decimal reference,
       60 digits of working precision, 30 printed. */
    expect_f("sqrtl(2)", sqrtl(2.0L), "1.41421356237309504880168872421e+00");
    expect_f("sqrtl(1e-40)", sqrtl(1e-40L), "1.00000000000000000000000000000e-20");
    expect_f("sqrtl(1e300)", sqrtl(1e300L), "1.00000000000000000000000000000e+150");
    expect_f("cbrtl(27)", cbrtl(27.0L), "3.00000000000000000000000000000e+00");
    expect_f("cbrtl(2)", cbrtl(2.0L), "1.25992104989487316476721060728e+00");
    expect_f("expl(1)", expl(1.0L), "2.71828182845904523536028747135e+00");
    expect_f("expl(-0.5)", expl(-0.5L), "6.06530659712633423603799534991e-01");
    expect_f("expl(10)", expl(10.0L), "2.20264657948067165169579006453e+04");
    expect_f("expl(0.001)", expl(0.001L), "1.00100050016670834166805575399e+00");
    expect_f("expm1l(1e-20)", expm1l(1e-20L), "1.00000000000000000000500000000e-20");
    expect_f("expm1l(0.5)", expm1l(0.5L), "6.48721270700128146848650787814e-01");
    expect_f("exp2l(3)", exp2l(3.0L), "8.00000000000000000000000000000e+00");
    expect_f("exp2l(0.5)", exp2l(0.5L), "1.41421356237309504880168872421e+00");
    expect_f("exp10l(2)", exp10l(2.0L), "1.00000000000000000000000000000e+02");
    expect_f("exp10l(-1)", exp10l(-1.0L), "1.00000000000000000000000000000e-01");
    expect_f("logl(2)", logl(2.0L), "6.93147180559945309417232121458e-01");
    expect_f("logl(10)", logl(10.0L), "2.30258509299404568401799145468e+00");
    expect_f("logl(1.5)", logl(1.5L), "4.05465108108164381978013115464e-01");
    expect_f("logl(1e-30)", logl(1e-30L), "-6.90775527898213705205397436405e+01");
    expect_f("log1pl(1e-20)", log1pl(1e-20L), "9.99999999999999999995000000000e-21");
    expect_f("log1pl(0.5)", log1pl(0.5L), "4.05465108108164381978013115464e-01");
    expect_f("log2l(8)", log2l(8.0L), "3.00000000000000000000000000000e+00");
    expect_f("log2l(3)", log2l(3.0L), "1.58496250072115618145373894395e+00");
    expect_f("log10l(2)", log10l(2.0L), "3.01029995663981195213738894724e-01");
    expect_f("log10l(1000)", log10l(1000.0L), "3.00000000000000000000000000000e+00");
    expect_f("sinl(1)", sinl(1.0L), "8.41470984807896506652502321630e-01");
    expect_f("sinl(0.5)", sinl(0.5L), "4.79425538604203000273287935216e-01");
    expect_f("sinl(-2)", sinl(-2.0L), "-9.09297426825681695396019865912e-01");
    expect_f("cosl(1)", cosl(1.0L), "5.40302305868139717400936607443e-01");
    expect_f("cosl(0.5)", cosl(0.5L), "8.77582561890372716116281582604e-01");
    expect_f("tanl(0.5)", tanl(0.5L), "5.46302489843790513255179465780e-01");
    expect_f("tanl(1)", tanl(1.0L), "1.55740772465490223050697480746e+00");
    expect_f("atanl(1)", atanl(1.0L), "7.85398163397448309615660845820e-01");
    expect_f("atanl(0.5)", atanl(0.5L), "4.63647609000806116214256231461e-01");
    expect_f("atanl(10)", atanl(10.0L), "1.47112767430373459185287557176e+00");
    expect_f("asinl(0.5)", asinl(0.5L), "5.23598775598298873077107230547e-01");
    expect_f("asinl(-0.3)", asinl(-0.3L), "-3.04692654015397507972002961228e-01");
    expect_f("acosl(0.5)", acosl(0.5L), "1.04719755119659774615421446109e+00");
    expect_f("acosl(-0.9)", acosl(-0.9L), "2.69056584179353080591799874749e+00");
    expect_f("sinhl(1)", sinhl(1.0L), "1.17520119364380145688238185060e+00");
    expect_f("sinhl(2)", sinhl(2.0L), "3.62686040784701876766821398280e+00");
    expect_f("coshl(1)", coshl(1.0L), "1.54308063481524377847790562076e+00");
    expect_f("coshl(2)", coshl(2.0L), "3.76219569108363145956221347777e+00");
    expect_f("tanhl(1)", tanhl(1.0L), "7.61594155955764888119458282605e-01");
    expect_f("tanhl(0.5)", tanhl(0.5L), "4.62117157260009758502318483644e-01");
    expect_f("powl(2,0.5)", powl(2.0L, 0.5L), "1.41421356237309504880168872421e+00");
    expect_f("powl(3,3)", powl(3.0L, 3.0L), "2.70000000000000000000000000000e+01");
    expect_f("powl(1.5,2.5)", powl(1.5L, 2.5L), "2.75567596063107536047194458404e+00");
    expect_f("powl(10,-3)", powl(10.0L, -3.0L), "1.00000000000000000000000000000e-03");
    expect_f("hypotl(3,4)", hypotl(3.0L, 4.0L), "5.00000000000000000000000000000e+00");
    expect_f("hypotl(1e-200,1e-200)", hypotl(1e-200L, 1e-200L), "1.41421356237309504880168872421e-200");
    expect_f("atan2l(1,2)", atan2l(1.0L, 2.0L), "4.63647609000806116214256231461e-01");
    expect_f("atan2l(-1,-1)", atan2l(-1.0L, -1.0L), "-2.35619449019234492884698253746e+00");

    /* ---- rounding to integer -------------------------------------------- */
    expect_x("floorl(2.5)", floorl(2.5L), 2.0L);
    expect_x("floorl(-2.5)", floorl(-2.5L), -3.0L);
    expect_x("ceill(2.5)", ceill(2.5L), 3.0L);
    expect_x("ceill(-2.5)", ceill(-2.5L), -2.0L);
    expect_x("truncl(-2.5)", truncl(-2.5L), -2.0L);
    expect_x("roundl(2.5)", roundl(2.5L), 3.0L);
    expect_x("roundl(-2.5)", roundl(-2.5L), -3.0L);
    expect_x("rintl(2.5)", rintl(2.5L), 2.0L);
    expect_x("rintl(3.5)", rintl(3.5L), 4.0L);
    expect_x("roundevenl(-2.5)", roundevenl(-2.5L), -2.0L);
    expect_x("nearbyintl(0.5)", nearbyintl(0.5L), 0.0L);
    /* A magnitude where the value still has a fraction bit but a 64-bit
     * integer cast could not represent it: 2^80 + 0.5. */
    expect_x("floorl(2^80+0.5)", floorl(ldexpl(1.0L, 80) + 0.5L), ldexpl(1.0L, 80));
    expect_x("ceill(2^80+0.5)", ceill(ldexpl(1.0L, 80) + 0.5L), ldexpl(1.0L, 80) + 1.0L);
    /* ...and one past the point where any fraction bit survives. */
    expect_x("floorl(2^120)", floorl(ldexpl(1.0L, 120) + 0.5L), ldexpl(1.0L, 120) + 0.5L);

    /* ---- remainder, splitting, scaling ----------------------------------- */
    expect_x("fmodl(10.5,3)", fmodl(10.5L, 3.0L), 1.5L);
    expect_x("fmodl(-10.5,3)", fmodl(-10.5L, 3.0L), -1.5L);
    expect_x("fmodl(0,3)", fmodl(0.0L, 3.0L), 0.0L);
    expect_x("modfl(3.75)", modfl(3.75L, &ip), 0.75L);
    expect_x("modfl ip", ip, 3.0L);
    expect_x("modfl(-3.75)", modfl(-3.75L, &ip), -0.75L);
    expect_x("modfl ip neg", ip, -3.0L);
    expect_x("frexpl(8)", frexpl(8.0L, &e), 0.5L);
    expect_i("frexpl(8) exp", e, 4);
    expect_x("ldexpl(0.5,4)", ldexpl(0.5L, 4), 8.0L);
    expect_x("scalbnl(1,3)", scalbnl(1.0L, 3), 8.0L);
    expect_x("scalblnl(1,-3)", scalblnl(1.0L, -3), 0.125L);
    /* frexp -> ldexp round trip, including two subnormal exponents */
    for (i = 0; i < 10; i++) {
        long double v = ldexpl(1.0L, exps[i]);
        long double m = frexpl(v, &e);
        expect_x("frexpl mantissa", m, 0.5L);
        expect_x("ldexpl back", ldexpl(m, e), v);
    }
    /* Scaling a subnormal up and back down has to be lossless. */
    expect_x("ldexpl subnormal round trip",
             ldexpl(ldexpl(LDBL_TRUE_MIN, 16000), -16000), LDBL_TRUE_MIN);

    /* ---- exponent extraction --------------------------------------------- */
    expect_i("ilogbl(8)", ilogbl(8.0L), 3);
    expect_i("ilogbl(1)", ilogbl(1.0L), 0);
    expect_i("ilogbl(0.5)", ilogbl(0.5L), -1);
    expect_i("ilogbl(0)", ilogbl(0.0L), FP_ILOGB0);
    expect_i("ilogbl(NaN)", ilogbl(0.0L / 0.0L), FP_ILOGBNAN);
    expect_x("logbl(8)", logbl(8.0L), 3.0L);
    /* a subnormal's true exponent, which is not what its exponent field says */
    expect_i("ilogbl(TRUE_MIN)", ilogbl(LDBL_TRUE_MIN), -16494);

    /* ---- neighbours -------------------------------------------------------- */
    expect_x("nextupl(1)", nextupl(1.0L), 1.0L + LDBL_EPSILON);
    expect_x("nextdownl(1)", nextdownl(1.0L), 1.0L - LDBL_EPSILON / 2.0L);
    expect_x("nextafterl(1,2)", nextafterl(1.0L, 2.0L), 1.0L + LDBL_EPSILON);
    expect_x("nextafterl(1,0)", nextafterl(1.0L, 0.0L), 1.0L - LDBL_EPSILON / 2.0L);
    /* Stepping off the top is infinity; stepping off the bottom is zero, and
     * nextafter(0) is the smallest subnormal rather than a second zero. */
    expect_i("nextafterl(MAX,inf) is inf", nextafterl(LDBL_MAX, 2.0L * LDBL_MAX) > LDBL_MAX, 1);
    expect_x("nextupl(-TRUE_MIN) is -0", fabsl(nextupl(-LDBL_TRUE_MIN)), 0.0L);
    expect_x("nextafterl(0,1)", nextafterl(0.0L, 1.0L), LDBL_TRUE_MIN);
    expect_x("nextafterl(0,-1)", nextafterl(0.0L, -1.0L), -LDBL_TRUE_MIN);
    expect_x("nextafterl(1,1)", nextafterl(1.0L, 1.0L), 1.0L);

    /* ---- min/max, sign, difference ---------------------------------------- */
    expect_x("fmaxl(1,NaN)", fmaxl(1.0L, 0.0L / 0.0L), 1.0L);
    expect_x("fminl(1,NaN)", fminl(1.0L, 0.0L / 0.0L), 1.0L);
    expect_x("fmaxl(-1,-2)", fmaxl(-1.0L, -2.0L), -1.0L);
    expect_i("fmaxl(NaN,NaN) is NaN", is_nanl(fmaxl(0.0L / 0.0L, 0.0L / 0.0L)), 1);
    expect_x("copysignl(1,-2)", copysignl(1.0L, -2.0L), -1.0L);
    expect_x("copysignl(1,-0)", copysignl(1.0L, -0.0L), -1.0L);
    expect_x("fdiml(1,2)", fdiml(1.0L, 2.0L), 0.0L);
    expect_x("fdiml(2,1)", fdiml(2.0L, 1.0L), 1.0L);
    expect_x("fabsl(-0)", fabsl(-0.0L), 0.0L);
    expect_x("cbrtl(-27)", cbrtl(-27.0L), -3.0L);

    /* ---- domain edges ------------------------------------------------------ */
    expect_i("sqrtl(-1) is NaN", is_nanl(sqrtl(-1.0L)), 1);
    expect_x("sqrtl(0)", sqrtl(0.0L), 0.0L);
    expect_i("expl(1e6) is inf", expl(1.0e6L) > LDBL_MAX, 1);
    expect_i("expl(-1e6) is 0", expl(-1.0e6L) == 0.0L, 1);
    expect_i("logl(0) is -inf", logl(0.0L) < -LDBL_MAX, 1);
    expect_i("logl(-1) is NaN", is_nanl(logl(-1.0L)), 1);
    expect_x("powl(0,0)", powl(0.0L, 0.0L), 1.0L);
    expect_x("powl(2,0)", powl(2.0L, 0.0L), 1.0L);
    expect_x("powl(-2,3)", powl(-2.0L, 3.0L), -8.0L);
    expect_i("powl(-2,0.5) is NaN", is_nanl(powl(-2.0L, 0.5L)), 1);
    expect_x("sinl(0)", sinl(0.0L), 0.0L);
    expect_x("cosl(0)", cosl(0.0L), 1.0L);
    expect_f("atanl(inf)", atanl(1.0L / 0.0L), "1.57079632679489661923132169164e+00");
    expect_i("sinl(inf) is NaN", is_nanl(sinl(1.0L / 0.0L)), 1);

    /* ---- identities: cheap, and they catch a constant with a wrong digit --- */
    {
        long double s = sinl(0.7L), c = cosl(0.7L);
        expect_near("sin^2+cos^2", s * s + c * c, 1.0L);
    }
    expect_near("exp(log(7))", expl(logl(7.0L)), 7.0L);
    expect_near("log(exp(3))", logl(expl(3.0L)), 3.0L);
    /* pow(2,10) goes through repeated squaring, which is exact -- an
     * exp/log path would land an ulp or two off 1024. */
    expect_x("pow(2,10)", powl(2.0L, 10.0L), 1024.0L);
    expect_near("sqrt(x)*sqrt(x)", sqrtl(3.0L) * sqrtl(3.0L), 3.0L);
    expect_near("tan = sin/cos", tanl(0.7L) - sinl(0.7L) / cosl(0.7L), 0.0L);
    expect_near("atan2 quadrant", atan2l(-1.0L, 1.0L) + atan2l(1.0L, 1.0L), 0.0L);
    expect_near("asin+acos", asinl(0.4L) + acosl(0.4L), 1.5707963267948966192313216916398L);
    expect_near("cosh^2-sinh^2", coshl(2.5L) * coshl(2.5L) - sinhl(2.5L) * sinhl(2.5L), 1.0L);
    expect_near("hypot vs sqrt", hypotl(1.0e300L, 1.0e300L), sqrtl(2.0L) * 1.0e300L);

    if (fails == 0) printf("OK\n");
    return fails == 0 ? 0 : 1;
}
