/* long double end-to-end test for the gocl back end.
 *
 * goc's long double is IEEE binary128 on every target, and this file exercises
 * the whole path that #47 wires up: the C source talks about `long double`, the
 * front end types it as KLongDouble, gocl lowers each operation to a call into
 * goclib's software runtime (goc_tf_*), and the result comes back as a 128-bit
 * integer the same shape as the runtime's { i64 lo, i64 hi } argument.
 *
 * The shift from "the runtime computes correctly" (tests/fp128/oracle.c checks
 * that bit for bit against libgcc) to "the front end and the back end agree on
 * the shape" is exactly what this file covers: literals, arithmetic, comparisons
 * producing a truth value, conversions in and out, compound assignment, and a
 * 200k-pair randomised battery folded into one FNV hash.
 *
 * How the hash is made trustworthy: the same battery is built twice. With
 * -DUSE_F128 every `long double` is gcc's __float128 (also binary128) and the
 * printed hash is the golden value. Without it the type is goc's long double and
 * the hash is compared against LD_HASH below. Because the two implementations
 * sit on the same bit pattern and the runtime already matches libgcc, the hashes
 * must be identical.
 *
 * Prints "OK" on the last line and exits 0 iff every check passed, so it drops
 * straight into build_run_win_ok() in tools/portability/win_regress.sh.
 *
 *   gcc -std=c11 -O2 -DUSE_F128 longdouble.c   # prints the golden hash
 */
#include <stdio.h>
#include <string.h>

#ifdef USE_F128
typedef __float128 T;
#define LITS(x) x##Q
#else
typedef long double T;
#define LITS(x) x##L
#endif

typedef struct { unsigned long long lo, hi; } pair;

static int fails = 0;

static unsigned long long st = 0x123456789ABCDEFull;
static unsigned long long nx(void) {
    st = st * 6364136223846793005ull + 1442695040888963407ull;
    return st ^ (st >> 32);
}

static void w_of(T x, unsigned long long *hi, unsigned long long *lo) {
    pair p;
    memcpy(&p, &x, 16);
    *lo = p.lo; *hi = p.hi;
}

/* The golden hash, produced by gcc -DUSE_F128: 0x5f90cf41ef671030ull. */
#define LD_HASH 0x5f90cf41ef671030ull

static unsigned long long h = 0xCBF29CE484222325ull;
#define MIXU(v) do { h ^= (unsigned long long)(v); h *= 0x100000001B3ull; } while (0)
#define MIXLD(x) do { unsigned long long _hi, _lo; w_of(x, &_hi, &_lo); MIXU(_hi); MIXU(_lo); } while (0)

static void w_d(double x, unsigned long long *u) { memcpy(u, &x, 8); }
static void w_f(float x, unsigned int *u) { memcpy(u, &x, 4); }

#ifndef USE_F128
/* Explicit expectations, generated by tests/fp128/ld_gold.c from gcc's
 * __float128. These pin the frontend literal path (1.5L must encode to the
 * right binary128) and the common arithmetic/conversion shapes. */
static void expect_ld(const char *name, T got,
                      unsigned long long hi, unsigned long long lo) {
    unsigned long long gh, gl;
    w_of(got, &gh, &gl);
    if (gh != hi || gl != lo) {
        printf("FAIL %s: got %016llx.%016llx want %016llx.%016llx\n",
               name, gh, gl, hi, lo);
        fails++;
    }
}
static void expect_d(const char *name, double got, unsigned long long bits) {
    unsigned long long u;
    w_d(got, &u);
    if (u != bits) {
        printf("FAIL %s: got %016llx want %016llx\n", name, u, bits);
        fails++;
    }
}
static void expect_f(const char *name, float got, unsigned int bits) {
    unsigned int u;
    w_f(got, &u);
    if (u != bits) {
        printf("FAIL %s: got %08x want %08x\n", name, u, bits);
        fails++;
    }
}
static void expect_ll(const char *name, long long got, unsigned long long bits) {
    unsigned long long u = (unsigned long long)got;
    if (u != bits) {
        printf("FAIL %s: got %016llx want %016llx\n", name, u, bits);
        fails++;
    }
}
#endif

int main(void) {
    int i;
    T a, b, r;
    for (i = 0; i < 200000; i++) {
        pair pa; pa.lo = nx(); pa.hi = nx();
        pair pb; pb.lo = nx(); pb.hi = nx();
        memcpy(&a, &pa, 16);
        memcpy(&b, &pb, 16);
        r = a + b; MIXLD(r);
        r = a - b; MIXLD(r);
        r = a * b; MIXLD(r);
        r = a / b; MIXLD(r);
        r = -a;    MIXLD(r);
        MIXU((unsigned long long)(a < b));
        MIXU((unsigned long long)(a > b));
        MIXU((unsigned long long)(a <= b));
        MIXU((unsigned long long)(a >= b));
        MIXU((unsigned long long)(a == b));
        MIXU((unsigned long long)(a != b));
        r = (T)(double)a;      MIXLD(r);
        r = (T)(float)a;       MIXLD(r);
        r = (T)(long long)a;   MIXLD(r);
        r = (T)(unsigned long long)a; MIXLD(r);
        {
            double d = (double)a; unsigned long long du; w_d(d, &du); MIXU(du);
            float f = (float)a;  unsigned int fu;     w_f(f, &fu);    MIXU(fu);
            long long ll = (long long)a;               MIXU((unsigned long long)ll);
            unsigned long long ull = (unsigned long long)a; MIXU(ull);
        }
    }

#ifndef USE_F128
    /* The explicit set. */
    {
        T a2 = LITS(1.5), b2 = LITS(2.25), third = LITS(1.0) / LITS(3.0);
        T big = LITS(1e30), tiny = LITS(1e-30);
        expect_ld("lit 1.5L", a2, 0x3fff800000000000ull, 0);
        expect_ld("lit 0.1L", LITS(0.1), 0x3ffb999999999999ull, 0x999999999999999aull);
        expect_ld("lit 1e30L", big, 0x406293e5939a08ceull, 0x9dbd480000000000ull);
        expect_ld("lit 1e-30L", tiny, 0x3f9b4484bfeebc29ull, 0xf863424b06f3529aull);
        expect_ld("lit 0x1.8p3L", LITS(0x1.8p3), 0x4002800000000000ull, 0);
        expect_ld("lit pi", LITS(3.14159265358979323846264338327950288),
                  0x4000921fb54442d1ull, 0x8469898cc51701b8ull);
        expect_ld("1.5+2.25", a2 + b2, 0x4000e00000000000ull, 0);
        expect_ld("1.5-2.25", a2 - b2, 0xbffe800000000000ull, 0);
        expect_ld("1.5*2.25", a2 * b2, 0x4000b00000000000ull, 0);
        expect_ld("1.5/2.25", a2 / b2, 0x3ffe555555555555ull, 0x5555555555555555ull);
        expect_ld("1/3", third, 0x3ffd555555555555ull, 0x5555555555555555ull);
        expect_ld("-(1.5)", -a2, 0xbfff800000000000ull, 0);
        expect_ld("1e30*1e-30", big * tiny, 0x3fff000000000000ull, 0);
        expect_ld("1e30+1e-30", big + tiny, 0x406293e5939a08ceull, 0x9dbd480000000000ull);
        expect_ld("1e30/0", big / LITS(0.0), 0x7fff000000000000ull, 0);
        expect_ld("0/0", LITS(0.0) / LITS(0.0), 0xffff800000000000ull, 0);
        expect_ld("1e30*1e30", big * big, 0x40c63e9e4e4c2f34ull, 0x448a03aec4845929ull);
        expect_ld("ld+double", a2 + 0.5, 0x4000000000000000ull, 0);
        expect_ld("double+ld", 0.5 + a2, 0x4000000000000000ull, 0);
        expect_ld("ld+float", a2 + 0.5f, 0x4000000000000000ull, 0);
        expect_ld("ld+int", a2 + 7, 0x4002100000000000ull, 0);
        expect_ld("ld+longlong", a2 + 7LL, 0x4002100000000000ull, 0);
        expect_ld("ld+uint", a2 + 7u, 0x4002100000000000ull, 0);
        {
            T x = a2; x += b2; expect_ld("x+=b", x, 0x4000e00000000000ull, 0);
            x *= LITS(2.0);   expect_ld("x*=2", x, 0x4001e00000000000ull, 0);
        }
        expect_ld("(ld)double", (T)0.1, 0x3ffb999999999999ull, 0xa000000000000000ull);
        expect_ld("(ld)float", (T)0.1f, 0x3ffb99999a000000ull, 0);
        expect_ld("(ld)int", (T)(-42), 0xc004500000000000ull, 0);
        expect_ld("(ld)uint", (T)4000000000u, 0x401edcd650000000ull, 0);
        expect_ld("(ld)ll", (T)(-9007199254740993LL), 0xc034000000000000ull, 0x0800000000000000ull);
        expect_d("(double)1.5L", (double)a2, 0x3ff8000000000000ull);
        expect_d("(double)1/3", (double)third, 0x3fd5555555555555ull);
        expect_d("(double)1e30", (double)big, 0x46293e5939a08ceaull);
        expect_d("(double)1e-30", (double)tiny, 0x39b4484bfeebc2a0ull);
        expect_f("(float)1.5L", (float)a2, 0x3fc00000u);
        expect_f("(float)1/3", (float)third, 0x3eaaaaabu);
        expect_ll("(long long)1.5L", (long long)a2, 0x0000000000000001ull);
        expect_ll("(long long)-1.5L", (long long)(-a2), 0xffffffffffffffffull);
        expect_ll("(long long)1e30L", (long long)big, 0x7fffffffffffffffull);
        expect_ll("(unsigned long long)1e30L", (unsigned long long)big, 0xffffffffffffffffull);

        /* comparisons produce a truth value, not a bit pattern */
        if (!((a2 < b2) == 1)) { printf("FAIL cmp a2<b2\n"); fails++; }
        if (!((a2 > b2) == 0)) { printf("FAIL cmp a2>b2\n"); fails++; }
        if (!((a2 == b2) == 0)) { printf("FAIL cmp a2==b2\n"); fails++; }
        if (!((a2 != b2) == 1)) { printf("FAIL cmp a2!=b2\n"); fails++; }
        /* NaN: every ordered comparison is false, only != is true */
        {
            T nanv = LITS(0.0) / LITS(0.0);
            if ((nanv < a2) != 0) { printf("FAIL cmp nan<\n"); fails++; }
            if ((nanv > a2) != 0) { printf("FAIL cmp nan>\n"); fails++; }
            if ((nanv == a2) != 0) { printf("FAIL cmp nan==\n"); fails++; }
            if ((nanv != a2) != 1) { printf("FAIL cmp nan!=\n"); fails++; }
        }
    }

    if (h != LD_HASH) {
        printf("FAIL hash: %016llx want %016llx\n", h, LD_HASH);
        fails++;
    }
#else
    printf("LD_HASH 0x%016llxull\n", h);
#endif

    printf("%s\n", fails ? "BAD" : "OK");
    return fails ? 1 : 0;
}
